#!/usr/bin/env python3
from panflute import run_filter

def do_something(doc):
    return


def action(elem, doc):
    pass


def main(doc=None):
    return run_filter(action,
                      prepare=do_something,
                      doc=doc)


if __name__ == "__main__":
    main()
